repos:
  - repo: local
    hooks:
      - id: check-yaml-compatibility
        name: Check YAML Template Backwards Compatibility
        entry: python scripts/check_compatibility.py
        language: python
        files: template\.yaml$
        additional_dependencies: [pyyaml==6.0.1]
      - id: archive-schema-version
        name: Archive Schema Version
        entry: python scripts/archive_schema.py
        language: python
        files: template\.yaml$
        additional_dependencies: [pyyaml==6.0.1]